[package]
name = "calculator_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
dashmap = "6.1.0"

[dev-dependencies]
assert_float_eq = "1.1.4"
rand = "0.8.5"